# Generated by Django 3.2.4 on 2021-06-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='percels.arealocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PicupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picupname', models.CharField(max_length=255)),
                ('picupaddress', models.CharField(max_length=1000)),
                ('shop_phone_number', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picup_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percels.arealocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Percel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percel_unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=1000)),
                ('product_weight', models.PositiveIntegerField(default=1)),
                ('product_price', models.PositiveIntegerField(default=1)),
                ('customerdetails', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_location', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percels.arealocation')),
                ('picuplocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percels.picuplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PercelComplete',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('percels.percel',),
        ),
        migrations.CreateModel(
            name='PercelProssesing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('percels.percel',),
        ),
        migrations.CreateModel(
            name='PercelPicUpAndDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PICUP', 'Picup'), ('DELIVERY', 'Delivery'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete')], max_length=50)),
                ('pipuprider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percelpicups', to='accounts.rider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('percel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percels.percelprossesing')),
            ],
        ),
    ]
