# Generated by Django 3.2.4 on 2021-06-23 17:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arealocations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percel_unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=1000)),
                ('product_weight', models.PositiveIntegerField(default=1)),
                ('product_price', models.PositiveIntegerField(default=1)),
                ('customerdetails', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_location', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arealocations.arealocation')),
            ],
        ),
    ]
