# Generated by Django 3.2.4 on 2021-06-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picuplocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('percels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percel',
            name='picuplocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picuplocations.picuplocation'),
        ),
        migrations.AddField(
            model_name='percel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PercelComplete',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('percels.percel',),
        ),
        migrations.CreateModel(
            name='PercelProssesing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('percels.percel',),
        ),
    ]
