# Generated by Django 3.2.4 on 2021-06-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PercelPicUpAndDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PICUP', 'Picup'), ('DELIVERY', 'Delivery'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete')], max_length=50)),
                ('pipuprider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percelpicups', to='accounts.rider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
