# Generated by Django 3.2.4 on 2021-06-25 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('percels', '0002_initial'),
        ('accounts', '0002_alter_account_area_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('percelpicupanddelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('delivery_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parceldeliveries', to='accounts.rider')),
            ],
        ),
        migrations.CreateModel(
            name='PercelPicUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('percel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percels.percel')),
                ('pipup_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percelpicups', to='accounts.rider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PercelPicUpAndDelivery',
        ),
        migrations.AddField(
            model_name='perceldelivery',
            name='picup_percel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percelpicupanddelivery.percelpicup'),
        ),
        migrations.AddField(
            model_name='perceldelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
